`controller`: Port changes from Wii decomp repo
open-ead/sead pull request #102
Opened 2022-03-27 18:30 UTC by MonsterDruide1

This PR adds all files from the recent changes regarding controller stuff from the Wii decomp repo. All functions are either matching or have been commented as being a mismatch.

In that route, I discovered that `TaskBase` seems to have another function, which is missing so far. As it really exists as a function and is not inlined in Super Mario Odyssey, the definition has to be added to a `cpp` later (when other functions are being implemented), so I just annotated what it should return for the moment.

2022-03-29 17:00 UTC, leoetlino requested changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/102)* status: all files reviewed, 56 unresolved discussions (waiting on @MonsterDruide1)

___
*[-- commits, line 8 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLY5oM6mSiJ9peFIFZ):*
Wii U, not Wii.
___
*[include/controller/seadAccelerometerAddon.h, line 15 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLYCJdCZ2SSeNcbWxF:-MzLYCJdCZ2SSeNcbWxG:b-8le9vp) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadAccelerometerAddon.h#L15)):*
> ```objc
> 
> public:
>     AccelerometerAddon(Controller* controller)
> ```

This should be marked `explicit`.
___
*[include/controller/seadAccelerometerAddon.h, line 21 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLYGbc1PtensXaaxG4:-MzLYGbc1PtensXaaxG5:b-6rljsq) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadAccelerometerAddon.h#L21)):*
> ```objc
>     }
> 
>     virtual ~AccelerometerAddon() {}
> ```

`= default` instead of `{}`
___
*[include/controller/seadControlDevice.h, line 16 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLYL7y1nme00_-nz_p:-MzLYL7zEaKPW8cafdFH:b4af60p) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControlDevice.h#L16)):*
> ```objc
> 
> public:
>     ControlDevice(ControllerMgr* mgr) : mId(ControllerDefine::cDevice_Null), mMgr(mgr) {}
> ```

explicit
___
*[include/controller/seadControlDevice.h, line 18 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLYLsP-ulkZFHmrmos:-MzLYLsP-ulkZFHmrmot:bxd39x5) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControlDevice.h#L18)):*
> ```objc
>     ControlDevice(ControllerMgr* mgr) : mId(ControllerDefine::cDevice_Null), mMgr(mgr) {}
> 
>     virtual ~ControlDevice() {}
> ```

= default
___
*[include/controller/seadControllerAddon.h, line 16 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZ-IB3JD6rJn1uxIg:-MzLZ-IB3JD6rJn1uxIh:b4af60p) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControllerAddon.h#L16)):*
> ```objc
> 
> public:
>     ControllerAddon(Controller* controller)
> ```

explicit
___
*[include/controller/seadControllerAddon.h, line 21 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZ05H4Z5Z9fcRblJ1:-MzLZ05H4Z5Z9fcRblJ2:bxd39x5) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControllerAddon.h#L21)):*
> ```objc
>     }
> 
>     virtual ~ControllerAddon() {}
> ```

= default
___
*[include/controller/seadControllerBase.h, line 10 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZ3rWDxsRVLF_Yl_0:-MzLZ3rWDxsRVLF_Yl_1:b-m3647k) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControllerBase.h#L10)):*
> ```objc
> namespace sead
> {
> typedef Vector2<s32> Vector2i;
> ```

This should be next to the other Vector type aliases in seadVector.h.
___
*[include/controller/seadControllerDefine.h, line 7 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZDZAEAr36g4oTqjM:-MzLZDZAEAr36g4oTqjN:bwrfs38) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControllerDefine.h#L7)):*
> ```objc
> namespace sead
> {
> // from Wii-decomp, not adjusted to switch
> ```

Wii U. sead didn't even exist in the Wii days!
___
*[include/controller/seadControllerMgr.h, line 102 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZQjTEhTIffsJMgZG:-MzLZQjTEhTIffsJMgZH:b2fx6qq) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControllerMgr.h#L102)):*
> ```objc
>     }
> 
>     return NULL;
> ```

nullptr
___
*[include/controller/seadControllerMgr.h, line 115 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZRdc7QqCqndmNx7d:-MzLZRdc7QqCqndmNx7e:b2fx6qq) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControllerMgr.h#L115)):*
> ```objc
>     }
> 
>     return NULL;
> ```

nullptr
___
*[include/controller/seadControllerMgr.h, line 125 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZSacDZ2HBRj-tNBM:-MzLZSacDZ2HBRj-tNBN:b2fx6qq) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControllerMgr.h#L125)):*
> ```objc
>         return controller->getAddonAs<T>();
> 
>     return NULL;
> ```

nullptr
___
*[include/controller/seadControllerWrapper.h, line 16 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZU1fBnbFIr2_jjF5:-MzLZU1fBnbFIr2_jjF6:bxd39x5) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControllerWrapper.h#L16)):*
> ```objc
> public:
>     ControllerWrapper();
>     virtual ~ControllerWrapper() {}
> ```

= default
___
*[include/controller/seadPatternRumbleAddon.h, line 12 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZWlp8wom2GRNHqKg:-MzLZWlp8wom2GRNHqKh:b4af60p) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadPatternRumbleAddon.h#L12)):*
> ```objc
> 
> public:
>     PatternRumbleAddon(Controller* controller);
> ```

explicit
___
*[include/controller/seadPatternRumbleAddon.h, line 13 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZXXt8EP_c-VwwkOw:-MzLZXXt8EP_c-VwwkOx:bxd39x5) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadPatternRumbleAddon.h#L13)):*
> ```objc
> public:
>     PatternRumbleAddon(Controller* controller);
>     virtual ~PatternRumbleAddon() {}
> ```

= default
___
*[include/controller/nin/seadNinJoyNpadDevice.h, line 18 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZasn93iqkrVAQdpy:-MzLZaso2O7PdNTmgzCe:b-xmxlws) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/nin/seadNinJoyNpadDevice.h#L18)):*
> ```objc
> 
> private:
>     void* filler[4292];
> ```

Could you convert this to a char/u8 array (and specify the size in hex)? Makes it easier to see the offsets and sizes.
___
*[include/framework/seadTaskBase.h, line 92 at r2](https://reviewable.io/reviews/open-ead/sead/102#-MzLY147ADeucC1tmOVH:-MzLY147ADeucC1tmOVI:b-62reod) ([raw file](https://github.com/open-ead/sead/blob/d042f575f9ebce5fe2ad9cca5d8b886e0836cffa/include/framework/seadTaskBase.h#L92)):*
> ```objc
>     virtual void onDestroy();
> 
>     DelegateThread* getFramework() const;  // seems to return mTaskMgr->mPreprareThread;
> ```

typo: mPrepareThread
___
*[include/math/seadVector.h, line 63 at r1](https://reviewable.io/reviews/open-ead/sead/102#-MzLXPZiEtUXO1s1u3bX:-MzLXPZiEtUXO1s1u3bY:bm8aq6l) ([raw file](https://github.com/open-ead/sead/blob/4bf7ea709b27845913832c76558682268718fd95/include/math/seadVector.h#L63)):*
> ```objc
>     T length() const
>     {
>         return sead::MathCalcCommon<T>::sqrt(this->x * this->x + this->y * this->y);
> ```

- This should probably be implemented in Vector2CalcCommon (see Vector3 and Vector3CalcCommon for an example).
- length() should also probably be implemented as sqrt(squaredLength()).
___
*[modules/src/controller/seadController.cpp, line 31 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzL_0pOEupDqQzwlZve:-MzL_0pOEupDqQzwlZvf:b6vpvze) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadController.cpp#L31)):*
> ```cpp
>     bool is_idle = true;
> 
>     for (OffsetList<ControllerAddon>::iterator it = mAddons.begin(); it  [...]

2022-03-29 17:03 UTC, leoetlino requested changes
a few more comments

> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/102#-:-MzLc7bU0dCcYvIqwzrH:bsiicab)* status: all files reviewed, 60 unresolved discussions (waiting on @MonsterDruide1)

___
*[include/controller/seadController.h, line 9 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLc2oJC9TDEGT5fQ7d:-MzLc2oJC9TDEGT5fQ7e:b-e838gr) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadController.h#L9)):*
> ```objc
> namespace
> {
> template <typename T>
> ```

This should be replaced with std::remove_pointer (don't forget to include `<type_traits>`).
___
*[include/controller/seadController.h, line 82 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLYWVg4WNBWNvScHdZ:-MzLYWVg4WNBWNvScHd_:b4af60p) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadController.h#L82)):*
> ```objc
>     };
> 
>     Controller(ControllerMgr* mgr);
> ```

explicit
___
*[include/controller/seadController.h, line 114 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLc0M81OEGVKrhKGdl:-MzLc0M81OEGVKrhKGdm:bb7da9g) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadController.h#L114)):*
> ```objc
> T Controller::getAddonAs() const
> {
>     for (OffsetList<ControllerAddon>::iterator it = mAddons.begin(); it != mAddons.end(); ++it)
> ```

auto
___
*[include/controller/seadController.h, line 121 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLYyiGDiJqsPa1E2gT:-MzLYyiGDiJqsPa1E2gU:b2fx6qq) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadController.h#L121)):*
> ```objc
>     }
> 
>     return NULL;
> ```

nullptr


<!-- Sent from Reviewable.io -->

2022-03-30 08:07 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/102)* status: 11 of 20 files reviewed, 60 unresolved discussions (waiting on @leoetlino and @MonsterDruide1)

___
*[-- commits, line 8 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLY5oM6mSiJ9peFIFZ):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Wii U, not Wii.
</blockquote></details>

Done.
___
*[include/controller/seadAccelerometerAddon.h, line 15 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLYCJdCZ2SSeNcbWxF:-MzOppQQ6jvznXecFMg9:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadAccelerometerAddon.h#L15)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This should be marked `explicit`.
</blockquote></details>

Done.
___
*[include/controller/seadAccelerometerAddon.h, line 21 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLYGbc1PtensXaaxG4:-MzOprdvB8Yb1RmyQ4z7:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadAccelerometerAddon.h#L21)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`= default` instead of `{}`
</blockquote></details>

Done.
___
*[include/controller/seadControlDevice.h, line 16 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLYL7y1nme00_-nz_p:-MzOpyg1-k6Z_aKxcppK:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControlDevice.h#L16)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

explicit
</blockquote></details>

Done.
___
*[include/controller/seadControlDevice.h, line 18 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLYLsP-ulkZFHmrmos:-MzOpz0xBzfgRNUPEvwI:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControlDevice.h#L18)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

= default
</blockquote></details>

Done.
___
*[include/controller/seadController.h, line 9 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLc2oJC9TDEGT5fQ7d:-MzOqKP1AcUKNtPcM3KK:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadController.h#L9)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This should be replaced with std::remove_pointer (don't forget to include `<type_traits>`).
</blockquote></details>

Done.
___
*[include/controller/seadController.h, line 82 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLYWVg4WNBWNvScHdZ:-MzOqMQM3juPIpifNYtN:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadController.h#L82)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

explicit
</blockquote></details>

Done.
___
*[include/controller/seadController.h, line 121 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLYyiGDiJqsPa1E2gT:-MzOqQr-C_7yHHRhHYlG:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadController.h#L121)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

nullptr
</blockquote></details>

Done.
___
*[include/controller/seadControllerAddon.h, line 16 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZ-IB3JD6rJn1uxIg:-MzOqTGY26HghFEVHky6:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControllerAddon.h#L16)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

explicit
</blockquote></details>

Done.
___
*[include/controller/seadControllerAddon.h, line 21 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZ05H4Z5Z9fcRblJ1:-MzOqV6bCcAPmuNfb7xL:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControllerAddon.h#L21)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

= default
</blockquote></details>

Done.
___
*[include/controller/seadControllerDefine.h, line 7 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZDZAEAr36g4oTqjM:-MzOqaOuDErFTDPK1RSC:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControllerDefine.h#L7)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Wii U. sead didn't even exist in the Wii days!
</blockquote></details>

Done.
___
*[include/controller/seadControllerMgr.h, line 102 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZQjTEhTIffsJMgZG:-MzOqetg-Do4fP9M05uc:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControllerMgr.h#L102)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

nullptr
</blockquote></details>

Done.
___
*[include/controller/seadControllerMgr.h, line 115 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZRdc7QqCqndmNx7d:-MzOqf9gAXwyM276JAHJ:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControllerMgr.h#L115)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

nullptr
</blockquote></details>

Done.
___
*[include/controller/seadControllerMgr.h, line 125 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZSacDZ2HBRj-tNBM:-MzOqfO0EomYUKD-3RJT:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControllerMgr.h#L125)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

nullptr
</blockquote></details>

Done.
___
*[include/controller/seadControllerWrapper.h, line 16 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZU1fBnbFIr2_jjF5:-MzOqm6lAHLa2AqK8vuT:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControllerWrapper.h#L16)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

= default
</blockquote></details>

Done.
___
*[include/controller/seadPatternRumbleAddon.h, line 12 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZWlp8wom2GRNHqKg:-MzOqvcS7ikxgR-8WOnm:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadPatternRumbleAddon.h#L12)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

explicit
</blockquote></details>

Done.
___
*[include/controller/seadPatternRumbleAddon.h, line 13 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZXXt8EP_c-VwwkOw:-MzOqvpd9ge-2M6aFedR:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadPatternRumbleAddon.h#L13)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

= default
</blockquote></details>

Done.
___
*[include/controller/nin/seadNinJoyNpadDevice.h, line 18 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZasn93iqkrVAQdpy:-MzOrDBO0EYFD4Ee4DOn:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/nin/seadNinJoyNpadDevice.h#L18)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Could you convert this to a char/u8 array (and specify the size in hex)? Makes it easier to see the offsets and sizes.
</blockquote></details>

Done.


<!-- Sent f [...]

2022-03-30 08:29 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/102)* status: 0 of 23 files reviewed, 59 unresolved discussions (waiting on @leoetlino and @MonsterDruide1)

___
*[include/controller/seadControllerBase.h, line 10 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZ3rWDxsRVLF_Yl_0:-MzOsojSC0CxXrijkQhE:bwv5zas) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControllerBase.h#L10)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This should be next to the other Vector type aliases in seadVector.h.
</blockquote></details>

I wasn't too sure this is an existing type, as it has never occured before. Done.
___
*[include/framework/seadTaskBase.h, line 92 at r2](https://reviewable.io/reviews/open-ead/sead/102#-MzLY147ADeucC1tmOVH:-MzOtBWA6xKZA1cx_-qI:bt2vr1b) ([raw file](https://github.com/open-ead/sead/blob/d042f575f9ebce5fe2ad9cca5d8b886e0836cffa/include/framework/seadTaskBase.h#L92)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

typo: mPrepareThread
</blockquote></details>

Fixed.
___
*[include/math/seadVector.h, line 63 at r1](https://reviewable.io/reviews/open-ead/sead/102#-MzLXPZiEtUXO1s1u3bX:-MzOtEyJEsUGc56ts8I9:bc3b2pi) ([raw file](https://github.com/open-ead/sead/blob/4bf7ea709b27845913832c76558682268718fd95/include/math/seadVector.h#L63)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

- This should probably be implemented in Vector2CalcCommon (see Vector3 and Vector3CalcCommon for an example).
- length() should also probably be implemented as sqrt(squaredLength()).
</blockquote></details>

Done. What about isZero? Does this function really exist, and where should it be implemented?
___
*[modules/src/controller/seadController.cpp, line 31 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzL_0pOEupDqQzwlZve:-MzOta311b3isDF0IHjH:bl8nc4l) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadController.cpp#L31)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`auto` (btw, does this match with a range-based for loop?)
</blockquote></details>

Done. (added `auto`). I couldn't create a proper range-based loop, as the compiler always complained about `ControllerAddon` being an abstract type... I couldn't find anything about that issue online, so I just thought of it as impossible. Does a rnage-based loop work on abstract types? (Leaving the other `auto`-notes open until this is resolved)
___
*[modules/src/controller/seadController.cpp, line 33 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZvz6-vtAxGoDsj6r:-MzOu7Tc7FIRO0C2HgoD:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadController.cpp#L33)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

it->
</blockquote></details>

Done.
___
*[modules/src/controller/seadController.cpp, line 44 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZulT1PBi_2MXEgCG:-MzOuDiC1zbG_gxeijvy:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadController.cpp#L44)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

it->
</blockquote></details>

Done.
___
*[modules/src/controller/seadController.cpp, line 83 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzL_Dqa6afYdLC9nWlJ:-MzOuGAS8scDB4p1Pj1S:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadController.cpp#L83)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

it->
</blockquote></details>

Done.
___
*[modules/src/controller/seadControllerBase.cpp, line 23 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzL_HGR2Z0-z2-zGvR2:-MzOuJGi9RioyRawgiqQ:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerBase.cpp#L23)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This should be uncommented.
</blockquote></details>

Done.
___
*[modules/src/controller/seadControllerBase.cpp, line 132 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzL_PPmER-Fk9RUbE_h:-MzOuLni768oGCg-sI4W:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerBase.cpp#L132)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This should be uncommented
</blockquote></details>

Done.
___
*[modules/src/controller/seadControllerBase.cpp, line 159 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzL_RkVEe4Ljnb-MQSx:-MzOuSKC6K-uGKzjECgw:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerBase.cpp#L159)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This should be uncommented
</blockquote></details>

Done.
___
*[modules/src/controller/seadControllerBase.cpp, line 173 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzL_SPw-i_MZlV2chE3:-MzOuSf25a7IGcgPZeKF:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerBase.cpp#L173)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This should be uncommented
</blockquote></details>

Done.
___
*[modules/src/controller/seadControllerMgr.cpp, line 38 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzL_hQe-yybaQ1_VcuD:-MzOuXs57WFNGT8OM-8X:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerMgr.cpp#L38)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

auto* (the parameter type already shows up on the right-hand side, there's no point in writing it twice)
</blockquote></details>

Done.
___
*[modules/src/controller/seadControllerMgr.cpp, line 41 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzL_fXhA_2C6oyPc0Xc:-MzOu_4M0NfFhEIHbLUm:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerMgr.cpp#L41)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

nullptr
</blockquote></details>

Done.
___
*[modules/src/controller/seadControllerMgr.cpp, line 47 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzL_gR763ftLHBxB4Jo:-MzOu_Hi8HV1yWAtJdte:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerMgr.cpp#L47)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

nullptr
</blockquote></details>

Done.
___
*[modules/src/controller/seadControllerMgr.cpp, line 64 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzL_rme8B20sP5prI_S:-MzOv88IBuPOvv4dt9IP:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerMgr.cpp#L64)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Could you turn this into a variable to make this more readable?
</blockquote></details>

Done.
___
*[modules/src/controller/seadControllerMgr.cpp, line 76 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLa3VB0zDIt9zDW4Ib:-MzOv29oAJid1wA9AZF9:b7w0fsz) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerMgr.cpp#L76)):*
<details><summary><i> [...]

2022-03-30 13:53 UTC, leoetlino reviewed
> Reviewed 9 of 9 files at r4, 23 of 23 files at r5, 1 of 1 files at r6, 13 of 18 files at r7, 5 of 5 files at r8, all commit messages.
> Dismissed @MonsterDruide1 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/102)* status: all files reviewed, 15 unresolved discussions (waiting on @MonsterDruide1)

___
*[include/controller/seadControllerBase.h, line 10 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZ3rWDxsRVLF_Yl_0:-MzQ56uF25d612xFAvVA:b-ipvm2c) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControllerBase.h#L10)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I wasn't too sure this is an existing type, as it has never occured before. Done.
</blockquote></details>

I think you may have forgotten to remove this? (It'll still compile fine but it's redundant considering you've added an identical type alias in seadVector.h)
___
*[include/math/seadVector.h, line 63 at r1](https://reviewable.io/reviews/open-ead/sead/102#-MzLXPZiEtUXO1s1u3bX:-MzQ2aAZ9XCf0w_uNs4a:b1bjksb) ([raw file](https://github.com/open-ead/sead/blob/4bf7ea709b27845913832c76558682268718fd95/include/math/seadVector.h#L63)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Done. What about isZero? Does this function really exist, and where should it be implemented?
</blockquote></details>

No idea, but implementing it inline in sead::Vector2 is probably fine.
___
*[modules/src/controller/seadController.cpp, line 31 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzL_0pOEupDqQzwlZve:-MzQ3E3CC68A2zKsF5co:burnlx2) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadController.cpp#L31)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Done. (added `auto`). I couldn't create a proper range-based loop, as the compiler always complained about `ControllerAddon` being an abstract type... I couldn't find anything about that issue online, so I just thought of it as impossible. Does a rnage-based loop work on abstract types? (Leaving the other `auto`-notes open until this is resolved)
</blockquote></details>

`for (auto& addon : addons)` should work. If you were doing `for (auto addon : addons)` (or `for (ControllerAddon addon : addons)`) it makes sense for the compiler to complain about ControllerAddon being an abstract type because you're asking it to copy every element from `addons`. You need that `&` to avoid unnecessary copies (and in this case, copying ControllerAddon is impossible, so you *must* use a reference).
___
*[modules/src/controller/seadControllerMgr.cpp, line 76 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLa3VB0zDIt9zDW4Ib:-MzQ4H0W2n35qDumqQG8:b-akfvu6) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerMgr.cpp#L76)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Done. Same for `finalizedDefault()`?
</blockquote></details>

Oh, I was thinking of only removing the debug stuff that was commented out. Oh well, I guess we might as well remove the rest, so yes, please go ahead and remove the #ifdef cafe stuff from finalizeDefault too.
___
*[modules/src/controller/seadControllerMgr.cpp, line 282 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLbQ3TE6paQfxtcTtN:-MzQ4i8O2ArdugpvF8Pw:b99pa8k) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerMgr.cpp#L282)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

What is the proper syntax on this one?
</blockquote></details>

Whoops, I think I commented on the wrong line! Disregard this comment :)
___
*[modules/src/controller/seadControllerMgr.cpp, line 289 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLbWVw0-PwS7dVYKbO:-MzQ4tdjAB_CwECFdrEv:b1k073r) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerMgr.cpp#L289)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Yes. There are only `sead::TaskBase::getFramework(void)` and `sead::ControllerMgr::getFramework(void)`, but those really have the name (according to SMO 1.0).
</blockquote></details>

Weird, but ok.


<!-- Sent from Reviewable.io -->

2022-03-30 14:21 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/102)* status: all files reviewed, 15 unresolved discussions (waiting on @leoetlino and @MonsterDruide1)

___
*[include/controller/seadController.h, line 114 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLc0M81OEGVKrhKGdl:-MzQBksX1CgZ6mYNilJQ:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadController.h#L114)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

auto
</blockquote></details>

Done.
___
*[include/controller/seadControllerBase.h, line 10 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLZ3rWDxsRVLF_Yl_0:-MzQ8bTk0MxcJhYwggSR:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/include/controller/seadControllerBase.h#L10)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

I think you may have forgotten to remove this? (It'll still compile fine but it's redundant considering you've added an identical type alias in seadVector.h)
</blockquote></details>

Done.
___
*[modules/src/controller/seadController.cpp, line 31 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzL_0pOEupDqQzwlZve:-MzQ8fZWC2gZ8DpKaf13:b-if7wmo) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadController.cpp#L31)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`for (auto& addon : addons)` should work. If you were doing `for (auto addon : addons)` (or `for (ControllerAddon addon : addons)`) it makes sense for the compiler to complain about ControllerAddon being an abstract type because you're asking it to copy every element from `addons`. You need that `&` to avoid unnecessary copies (and in this case, copying ControllerAddon is impossible, so you *must* use a reference).
</blockquote></details>

Ah, right, I forgot the reference! Alright, I went through all other loops with `auto` comment and checked if they match with a range-based loop, and kept the iterator wherever neccessary.
___
*[modules/src/controller/seadController.cpp, line 42 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzL_91B9Unab7LGbtk_:-MzQ8GRWA9kpdX1JBnWP:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadController.cpp#L42)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

auto
</blockquote></details>

Done.
___
*[modules/src/controller/seadController.cpp, line 58 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzL_AcjDh2VzWZZQKqW:-MzQ8FzB9Iy9M9IhWXyC:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadController.cpp#L58)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

auto
</blockquote></details>

Done.
___
*[modules/src/controller/seadController.cpp, line 81 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzL_DAa7qDxNV2J9ztA:-MzQ8Fo0-4BkYgKRAok6:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadController.cpp#L81)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

auto
</blockquote></details>

Done.
___
*[modules/src/controller/seadControllerMgr.cpp, line 76 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLa3VB0zDIt9zDW4Ib:-MzQ97n41Pc-q3DVS_7M:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerMgr.cpp#L76)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Oh, I was thinking of only removing the debug stuff that was commented out. Oh well, I guess we might as well remove the rest, so yes, please go ahead and remove the #ifdef cafe stuff from finalizeDefault too.
</blockquote></details>

Done.
___
*[modules/src/controller/seadControllerMgr.cpp, line 201 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLb4fz8s8DOGsIJPFO:-MzQ9YC5-29DpEqJJW9J:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerMgr.cpp#L201)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

auto
</blockquote></details>

Done.
___
*[modules/src/controller/seadControllerMgr.cpp, line 219 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLb9_S2Z_WcND4npM6:-MzQAXpXAZQeMdxB7VuT:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerMgr.cpp#L219)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

auto
</blockquote></details>

Done.
___
*[modules/src/controller/seadControllerMgr.cpp, line 222 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLbFl56Fs1obkQ-f8N:-MzQAY60BVCIt2Fn3fFR:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerMgr.cpp#L222)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

auto
</blockquote></details>

Done.
___
*[modules/src/controller/seadControllerMgr.cpp, line 228 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLbHOw7S3yFxN5X1wA:-MzQAqj6BDPYCJMAbeGa:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerMgr.cpp#L228)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

auto
</blockquote></details>

Done.
___
*[modules/src/controller/seadControllerMgr.cpp, line 245 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLbKO-7DyRJhGJOnUB:-MzQAzPB2Rh7ASchwbGU:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerMgr.cpp#L245)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

auto
</blockquote></details>

Done.
___
*[modules/src/controller/seadControllerMgr.cpp, line 280 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLbPGf2Nci-Bph-Lxw:-MzQB9hj2W-scwgXcexn:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerMgr.cpp#L280)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

auto
</blockquote></details>

Done.
___
*[modules/src/controller/seadControllerMgr.cpp, line 282 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLbQ3TE6paQfxtcTtN:-MzQBER_8UzVzUYr70kb:b-i1ctdw) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerMgr.cpp#L282)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Whoops, I think I commented on the wrong line! Disregard this comment :)
</blockquote></details>

Fixed it through range-based iteration either way :)
___
*[modules/src/controller/seadControllerWrapperBase.cpp, line 57 at r3](https://reviewable.io/reviews/open-ead/sead/102#-MzLbf8g0iYJj_wA55UZ:-MzQBbfTDJk87H3f45Ac:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/9f551bce05ec090711ebee7578a5009df380c7ef/modules/src/controller/seadControllerWrapperBase.cpp#L57)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

auto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-30 14:31 UTC, leoetlino requested changes
> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/102)* status: all files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1)

___
*[include/controller/seadController.h, line 86 at r9](https://reviewable.io/reviews/open-ead/sead/102#-MzQDFYn58JaNU9fu-XS:-MzQDFYn58JaNU9fu-XT:b-thz80g) ([raw file](https://github.com/open-ead/sead/blob/613556a259e7971d3d95d918fb4924862d1dcd2a/include/controller/seadController.h#L86)):*
> ```objc
>     for (auto& addon : mAddons)
>     {
>         return addon;
> ```

I don't think removing the DynamicCast is correct. You still want to check whether the addon has the correct dynamic type (*and* this will not compile anyway, because you're returning `ControllerAddon&` when the function return type is T, and T is a pointer).


<!-- Sent from Reviewable.io -->

2022-03-30 15:43 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/102)* status: 3 of 23 files reviewed, 1 unresolved discussion (waiting on @leoetlino)

___
*[include/controller/seadController.h, line 86 at r9](https://reviewable.io/reviews/open-ead/sead/102#-MzQDFYn58JaNU9fu-XS:-MzQTvFC7ETJJLp4fXCQ:b-wl76ng) ([raw file](https://github.com/open-ead/sead/blob/613556a259e7971d3d95d918fb4924862d1dcd2a/include/controller/seadController.h#L86)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

I don't think removing the DynamicCast is correct. You still want to check whether the addon has the correct dynamic type (*and* this will not compile anyway, because you're returning `ControllerAddon&` when the function return type is T, and T is a pointer).
</blockquote></details>

Okay, I added the DynamicCast again. I can't verify this function, as it is never generated (and doesn't even exist in the SMO decomp).
___
*[include/math/seadVector.h, line 63 at r1](https://reviewable.io/reviews/open-ead/sead/102#-MzLXPZiEtUXO1s1u3bX:-MzQUXI8AFWNQ5kBW2m1:b-9491ra) ([raw file](https://github.com/open-ead/sead/blob/4bf7ea709b27845913832c76558682268718fd95/include/math/seadVector.h#L63)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

No idea, but implementing it inline in sead::Vector2 is probably fine.
</blockquote></details>

So keeping it like it is at the moment?


<!-- Sent from Reviewable.io -->

2022-03-30 20:18 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/102)* status: 3 of 23 files reviewed, 1 unresolved discussion (waiting on @leoetlino)

___
*[include/controller/seadController.h, line 86 at r9](https://reviewable.io/reviews/open-ead/sead/102#-MzQDFYn58JaNU9fu-XS:-MzRTXglB3pn3sn0AcoD:bmqemzl) ([raw file](https://github.com/open-ead/sead/blob/613556a259e7971d3d95d918fb4924862d1dcd2a/include/controller/seadController.h#L86)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This is still incorrect. This will always return nullptr unless the first addon in the list happens to have the correct dynamic type.

This should be:

```c++
for (auto& addon : mAddons)
{
    T result = DynamicCast<std::remove_pointer_t<T>>(addon);
    if (result)
        return result;
}
```

(also `remove_pointer<T>::type` -> `remove_pointer_t<T>`)
</blockquote></details>

Ohh, I thought `DynamicCast` would just force a conversion, no matter if it works or not. Inserted your code now.


<!-- Sent from Reviewable.io -->

2022-03-31 08:13 UTC, leoetlino approved these changes
> Reviewed 20 of 20 files at r13, 1 of 1 files at r14, 18 of 18 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/102)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MonsterDruide1)



<!-- Sent from Reviewable.io -->

2022-03-31 08:13 UTC, merged