heap: Implement seadHeapMgr and seadArena
open-ead/sead pull request #105
Opened 2022-08-06 16:45 UTC by MonsterDruide1

Two `NON_MATCHING`s on this one:
1. `HeapMgr::destroy` cleans up two static variables and destroys all heaps from the lists. However, I can't find the right iterator for this one, so I just listed all three versions I tried there. (https://decomp.me/scratch/saxAV)
2. `HeapMgr::findContainHeap` looks a bit too lengthy overall - especially looking at the CriticalSection-mutex. (https://decomp.me/scratch/QPDI8)

Apart from that, I added a few functions to `FindContainHeapCache`, which partly seem useless to me - but I can't keep up the match level with fewer functions, as I don't know enough about how Atomics are used here.

2022-08-06 18:45 UTC, leoetlino requested changes
> Reviewed 3 of 3 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/105)* status: all files reviewed, 27 unresolved discussions (waiting on @MonsterDruide1)

___
*[`include/heap/seadHeapMgr.h` line 42 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oNjB5--Votxdt1zV7:-N8oNjB5--Votxdt1zV8:b3vg1x5) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L42)):*
> ```objc
>     static void removeRootHeap(Heap*);
> 
>     IDelegate1<const AllocFailedCallbackArg*>*
> ```

Consider adding a type alias (`using IAllocFailedCallback = IDelegate1<...>`) for this.

(`IAllocFailedCallback` is the original name of the type alias according to debug info for Super Mario Run's copy of pead).
___
*[`include/heap/seadHeapMgr.h` line 43 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oNz1m3coNHniXg_X6:-N8oNz1nArxz6oTJe9mB:bev40wo) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L43)):*
> ```objc
> 
>     IDelegate1<const AllocFailedCallbackArg*>*
>     setAllocFailedCallback(IDelegate1<const AllocFailedCallbackArg*>* callback);
> ```

Might be worth adding `IAllocFailedCallback * getAllocFailedCallback();` as well (yes, Nintendo forgot to const qualify it :/)
___
*[`include/heap/seadHeapMgr.h` line 48 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oP18O-qk7JvsUrPKc:-N8oP18O-qk7JvsUrPKd:b-na2nql) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L48)):*
> ```objc
>     static s32 getRootHeapNum() { return sRootHeaps.size(); }
> 
>     static Arena* sArena;
> ```

This should be below the TODO comment because that also applies to the sArena variable you just added.
___
*[`include/heap/seadHeapMgr.h` line 66 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oOARkE7vMAOsY75xY:-N8oOARkE7vMAOsY75xZ:b-mbi3kv) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L66)):*
> ```objc
>     static IndependentHeaps sIndependentHeaps;
>     static CriticalSection sHeapTreeLockCS;
>     static s64 sSleepSpanAtRemoveCacheFailure;
> ```

Are you sure this isn't a TickSpan?
___
*[`include/heap/seadHeapMgr.h` line 68 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oOiJ-BleAs3naqVe_:-N8oOiJ-BleAs3naqVea:b-gfnae) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L68)):*
> ```objc
>     static s64 sSleepSpanAtRemoveCacheFailure;
> 
>     Heap* mAllocFromNotSeadThreadHeap;
> ```

might be worth adding a comment to explain what this is (fallback heap that is returned when getting the current heap outside of an sead::Thread) because Nintendo's name is pretty terrible (IMO)
___
*[`include/heap/seadHeapMgr.h` line 116 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oPNp13kkK73nxdDo9:-N8oPNp13kkK73nxdDoA:bjrbosa) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L116)):*
> ```objc
>     Heap* getHeap() const;
>     void setHeap(Heap* heap) { mHeap.storeNonAtomic(uintptr_t(heap)); }
>     void removeHeap(Heap* heap) { mHeap.fetchAnd(~1LL); }
> ```

`heap` is unused. Is that intended?
___
*[`include/heap/seadHeapMgr.h` line 117 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oPAMpDdSVOuNTnKPg:-N8oPAMpDdSVOuNTnKPh:b-enu4n7) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L117)):*
> ```objc
>     void setHeap(Heap* heap) { mHeap.storeNonAtomic(uintptr_t(heap)); }
>     void removeHeap(Heap* heap) { mHeap.fetchAnd(~1LL); }
>     // getHeap and setHeap probably exist too
> ```

This comment should be removed now that you have added getHeap and setHeap.
___
*[`include/thread/seadThread.h` line 88 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oPWEC0OG826qxEYmz:-N8oPWEC0OG826qxEYn-:b-yb62e7) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/thread/seadThread.h#L88)):*
> ```objc
>     Heap* setCurrentHeap(Heap* heap)
>     {
>         Heap* old = mCurrentHeap;
> ```

`return std::exchange(mCurrentHeap, heap);` (`#include <utility>` for [std::exchange](https://en.cppreference.com/w/cpp/utility/exchange))
___
*[`include/thread/seadThread.h` line 155 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oPhNy8dZQOznbEbpn:-N8oPhNy8dZQOznbEbpo:b74jye6) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/thread/seadThread.h#L155)):*
> ```objc
>     bool tryRemoveFromFindContainHeapCache(Heap* heap)
>     {
>         auto back = mList.end();
> ```

`const auto end`
___
*[`include/thread/seadThread.h` line 158 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oPjdU-50LSpmI7p8p:-N8oPjdU-50LSpmI7p8q:b-jm5dlg) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/thread/seadThread.h#L158)):*
> ```objc
>         ScopedLock<CriticalSection> lock(getListCS());
>         bool found = false;
>         for (auto it = mList.begin(), end = back; it != end; ++it)
> ```

...and then remove `end = back` because your end iterator is already called `end`.
___
*[`include/thread/seadThread.h` line 193 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oPuMd3h7p-79VzyAW:-N8oPuMd3h7p-79VzyAX:b-tnisgh) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/thread/seadThread.h#L193)):*
> ```objc
>     static u32 getCurrentThreadID_();
> 
> public:
> ```

Please don't.
___
*[`modules/src/heap/seadArena.cpp` line 6 at r1](https://reviewable.io/reviews/open-ead/sead/105#-N8oMr259UnYL2QSU4mQ:-N8oMr259UnYL2QSU4mR:b-v6va1q) ([raw file](https://github.com/open-ead/sead/blob/b0da4bf710d70c4bdb18e7d7e9554ac46c7728fb/modules/src/heap/seadArena.cpp#L6)):*
> ```cpp
> namespace sead
> {
> Arena::Arena() {}
> ```

= default;
___
*[`modules/src/heap/seadArena.cpp` line 11 at r1](https://reviewable.io/reviews/open-ead/sead/105#-N8oNGL61AiRjM2rbL2x:-N8oNGL61AiRjM2rbL2y:bf5dtk) ([raw file](https://github.com/open-ead/sead/blob/b0da4bf710d70c4bdb18e7d7e9554ac46c7728fb/modules/src/heap/seadArena.cpp#L11)):*
> ```cpp
> void Arena::initialize(size_t size)
> {
>     nn::os::AllocateMemoryBlock(reinterpret_cast<u64*>(&mStart),
> ```

`uintptr_t*` (as mStart is a pointer)
___
*[`modules/src/heap/seadArena.cpp` line 18 at r1](https://reviewable.io/reviews/open-ead/sead/105#-N8oNPjH4f0imMST9zOB:-N8oNPjH4f0imMST9zOC:b-zeeaz8) ([raw file](https://github.com/open-ead/sead/blob/b0da4bf710d70c4bdb18e7d7e9554ac46c7728fb/modules/src/heap/seadArena.cpp#L18)):*
> ```cpp
> void Arena::destroy()
> {
>     if (!mInitWithStartAddress)
> ```

This if statement should be braced because it spans more than one line
___
*[`modules/src/heap/seadHeapMgr.cpp` line 19 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oPz8QDZlA2DoZcVly:-N8oPz8QDZlA2DoZcVlz:b-nlp5mp) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L19)):*
> ```cpp
> CriticalSection HeapMgr::sHeapTreeLockCS;
> 
> HeapMgr::HeapMgr() : mAllocFromNotSeadThreadHeap(NULL), mAllocFailedCallback(NULL) {}
> ```

These can be in-class initialised (e.g. do `Heap* mAllocFromNotSeadThreadHeap = nullptr;` when the member variable is declared in the class definition).
___
*[`modules/src/heap/seadHeapMgr.cpp` line 28 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oQ8Oe3j2lyR2maxVB:-N8oQ8Of9kmJ8b1fYvr9:b-cddcab) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L28)):*
> ```cpp
>     initializeImpl_();
>     sHeapTreeLockCS.unlock();
> }
> ```

Please add line break [...]

2022-08-07 09:54 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/105)* status: all files reviewed, 27 unresolved discussions (waiting on @leoetlino and @MonsterDruide1)

___
*[`include/heap/seadHeapMgr.h` line 42 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oNjB5--Votxdt1zV7:-N8rfl6Q9ow2L-8Oo6tN:bgw6jwv) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L42)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Consider adding a type alias (`using IAllocFailedCallback = IDelegate1<...>`) for this.

(`IAllocFailedCallback` is the original name of the type alias according to debug info for Super Mario Run's copy of pead).
</blockquote></details>

Done. Is there more info in the Super Mario Run debugging stuff that could be used for `sead` implementation?
___
*[`include/heap/seadHeapMgr.h` line 43 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oNz1m3coNHniXg_X6:-N8rfrto7bG9p3TZWz2K:b-iwrjzx) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L43)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Might be worth adding `IAllocFailedCallback * getAllocFailedCallback();` as well (yes, Nintendo forgot to const qualify it :/)
</blockquote></details>

I don't have that method in Super Mario Odyssey. Was it optimized away, or does it only exist as inline function?
___
*[`include/heap/seadHeapMgr.h` line 48 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oP18O-qk7JvsUrPKc:-N8rgCcrE40Mkr43w92E:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L48)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This should be below the TODO comment because that also applies to the sArena variable you just added.
</blockquote></details>

Done.
___
*[`include/heap/seadHeapMgr.h` line 66 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oOARkE7vMAOsY75xY:-N8rg_yU3SlGEoBkngh-:b-pksutw) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L66)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Are you sure this isn't a TickSpan?
</blockquote></details>

No, I just had `s64` there before without re-thinking if `TickSpan` would match too. Fixed.
___
*[`include/heap/seadHeapMgr.h` line 68 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oOiJ-BleAs3naqVe_:-N8rgvvZ7csQp7WDmQeq:ba8j4yi) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L68)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

might be worth adding a comment to explain what this is (fallback heap that is returned when getting the current heap outside of an sead::Thread) because Nintendo's name is pretty terrible (IMO)
</blockquote></details>

Yes, absolutely. Added.
___
*[`include/heap/seadHeapMgr.h` line 116 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oPNp13kkK73nxdDo9:-N8rhMSP1NPDTGO36BO7:b9puya4) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L116)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`heap` is unused. Is that intended?
</blockquote></details>

It is not required for the logic, as this function only ANDs with 0xFF...FE, but apparently there is no change in codegen when removing it - so I just removed it.

Does that name even match here? Should the functions be moved into `cpp`?
___
*[`include/heap/seadHeapMgr.h` line 117 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oPAMpDdSVOuNTnKPg:-N8rhmuU6eRwNTQFhvLw:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L117)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This comment should be removed now that you have added getHeap and setHeap.
</blockquote></details>

Done.
___
*[`include/thread/seadThread.h` line 88 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oPWEC0OG826qxEYmz:-N8ri6CC6KHtjoTyyG1n:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/thread/seadThread.h#L88)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`return std::exchange(mCurrentHeap, heap);` (`#include <utility>` for [std::exchange](https://en.cppreference.com/w/cpp/utility/exchange))
</blockquote></details>

Done.
___
*[`include/thread/seadThread.h` line 155 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oPhNy8dZQOznbEbpn:-N8riIlHAyi91i2sXgkM:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/thread/seadThread.h#L155)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`const auto end`
</blockquote></details>

Done.
___
*[`include/thread/seadThread.h` line 158 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oPjdU-50LSpmI7p8p:-N8riIzpEnFd9Ju67ZOv:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/thread/seadThread.h#L158)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

...and then remove `end = back` because your end iterator is already called `end`.
</blockquote></details>

Done.
___
*[`include/thread/seadThread.h` line 193 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oPuMd3h7p-79VzyAW:-N8riOfnC_G62Klw9wSC:b-da7pbj) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/thread/seadThread.h#L193)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Please don't.
</blockquote></details>

Yes, forgot to revert that again. Fixed.


<!-- Sent from Reviewable.io -->

2022-08-07 10:34 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/105)* status: 4 of 7 files reviewed, 27 unresolved discussions (waiting on @leoetlino and @MonsterDruide1)

___
*[`modules/src/heap/seadArena.cpp` line 6 at r1](https://reviewable.io/reviews/open-ead/sead/105#-N8oMr259UnYL2QSU4mQ:-N8riv4_7dfzOPJM-w4w:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/b0da4bf710d70c4bdb18e7d7e9554ac46c7728fb/modules/src/heap/seadArena.cpp#L6)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

= default;
</blockquote></details>

Done.
___
*[`modules/src/heap/seadArena.cpp` line 11 at r1](https://reviewable.io/reviews/open-ead/sead/105#-N8oNGL61AiRjM2rbL2x:-N8rjAMWCJcf3pdLB2RS:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/b0da4bf710d70c4bdb18e7d7e9554ac46c7728fb/modules/src/heap/seadArena.cpp#L11)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`uintptr_t*` (as mStart is a pointer)
</blockquote></details>

Done.
___
*[`modules/src/heap/seadArena.cpp` line 18 at r1](https://reviewable.io/reviews/open-ead/sead/105#-N8oNPjH4f0imMST9zOB:-N8rjGAcAi_nVQS6XQm4:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/b0da4bf710d70c4bdb18e7d7e9554ac46c7728fb/modules/src/heap/seadArena.cpp#L18)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This if statement should be braced because it spans more than one line
</blockquote></details>

Done.
___
*[`modules/src/heap/seadHeapMgr.cpp` line 19 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oPz8QDZlA2DoZcVly:-N8rjdyDB9TLDbFdvITr:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L19)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

These can be in-class initialised (e.g. do `Heap* mAllocFromNotSeadThreadHeap = nullptr;` when the member variable is declared in the class definition).
</blockquote></details>

Done.
___
*[`modules/src/heap/seadHeapMgr.cpp` line 28 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oQ8Oe3j2lyR2maxVB:-N8rk1z84QAOk9HNrjUW:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L28)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Please add line breaks between functions to improve code readability.
</blockquote></details>

Done.
___
*[`modules/src/heap/seadHeapMgr.cpp` line 43 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oQFy1Cp7Gmil8ozeX:-N8rk5b04wdEAqszPD90:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L43)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`auto*` -- it is obvious that tryCreate is some kind of factory function, and the type name (ExpHeap) already appears explicitly on the right-hand side. The variable is also called expHeap already so there is really no need to write the type name explicitly!
</blockquote></details>

Done.
___
*[`modules/src/heap/seadHeapMgr.cpp` line 53 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oR6_E0s2L79juk5Li:-N8rkKK-BV2Q1YDvc-6A:bndzu7k) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L53)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

I'd just write this the obvious, idiomatic way and not care about matching this at the moment -- there's probably something wrong in PtrArray::popBack

```
while (sIndependentHeaps.isEmpty())
{
    sIndependentHeaps.back()->destroy();
    sIndependentHeaps.popBack();
}
```
</blockquote></details>

Done. I wanted to keep it in for reference on future attempts of matching, but I can just simplify them too.
___
*[`modules/src/heap/seadHeapMgr.cpp` line 71 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oRYKcCfRxKyEQIjzT:-N8rkQyQ6vQVHClzEaKo:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L71)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Commented out code is code that shouldn't be PRd.
</blockquote></details>

Done.
___
*[`modules/src/heap/seadHeapMgr.cpp` line 74 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oRbhmC7FRJHDKQsie:-N8rkRG_EXmr_TsaAhAb:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L74)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`modules/src/heap/seadHeapMgr.cpp` line 94 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oRzBp1EReDXgfQ-NH:-N8rqduh0OsHuz2dZWtM:b-rbt3t7) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L94)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This is really really messy and some variables even still have Hex-Rays style placeholder names and doesn't match either. I think we should leave this function alone for now and revisit when you have a more readable match.
</blockquote></details>

One of the first things I wanted to do in cleanup is the lock, but I can't figure out how that is handled. The method seems to be divided up into two parts, with the first one requiring the currentThread and the second one handling static variables `sRootHeaps` and `sIndependentHeaps`. However, I have no idea how the lock is carried between these two parts without unlocking and re-locking using a ScopedLock, so I'm lost on how to optimize this function - that's why I created the `decompme`, to allow you making quick suggestions on how to improve it.
___
*[`modules/src/heap/seadHeapMgr.cpp` line 199 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oSnfS5Y4l_iefRuzo:-N8rm6Tn7NlVZi5p0buq:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L199)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

I'd suggest removing the braces for the if statement to improve code readability (by making things a bit denser vertically)
</blockquote></details>

Done.
___
*[`modules/src/heap/seadHeapMgr.cpp` line 233 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oT8rcEBnnrFLcbTBw:-N8rmEiW9vOeqyiJ6aBe:b-yk2w9g) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L233)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

auto*, braces, line breaks, etc.
</blockquote></details>

Changed to auto*, where would you do what with braces?
___
*[`modules/src/heap/seadHeapMgr.cpp` line 252 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oTEAH3m38MMkDgss9:-N8rqNQ351gY0kj_1U04:b-9w2h1r) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L252)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

consider using makeScopedLock to avoid the need to write the entire ScopedLock type explicitly
</blockquote></details>

This does not work here for some reason:
```
auto lock = makeScopedLock(sHeapTreeLockCS);
```
=>
```
/home/monsterdruide1/OdysseyDecompSead/OdysseyDecomp/lib/sead/include/prim/seadScopedLock.h:21:12: error: call to deleted constructor of 'ScopedLock<sead::CriticalSection>'
    return ScopedLock<T>(&lock);
           ^~~~~~~~~~~~~~~~~~~~
/home/monsterdruide1/OdysseyDecompSead/OdysseyDecomp/lib/sead/modules/src/heap/seadHeapMgr.cpp:237:17: note: in instantia [...]

2022-08-07 22:07 UTC, leoetlino reviewed
> Reviewed 5 of 5 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/105)* status: all files reviewed, 7 unresolved discussions (waiting on @leoetlino and @MonsterDruide1)

___
*[`include/heap/seadHeapMgr.h` line 42 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oNjB5--Votxdt1zV7:-N8uInIA3poF1R33lS-m:b-oemy09) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L42)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Done. Is there more info in the Super Mario Run debugging stuff that could be used for `sead` implementation?
</blockquote></details>

Grab a recent (but not too recent) APK of Super Mario Run and then extract libnn_piaPlugin.so from it. Then load the shared library into gdb (or another tool of your choice) to see the debug info.

With gdb the command you'll want to use to see debug info is `ptype`.

---

I see you have added the type alias, but don't forget to use it :)
___
*[`include/heap/seadHeapMgr.h` line 43 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oNz1m3coNHniXg_X6:-N8uJ2Cm-hn_MLoNCHoo:bl3opbw) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L43)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I don't have that method in Super Mario Odyssey. Was it optimized away, or does it only exist as inline function?
</blockquote></details>

It's probably inline.
___
*[`include/heap/seadHeapMgr.h` line 116 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oPNp13kkK73nxdDo9:-N8uJsFYEghZlnbMjXul:btrdbet) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L116)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

It is not required for the logic, as this function only ANDs with 0xFF...FE, but apparently there is no change in codegen when removing it - so I just removed it.

Does that name even match here? Should the functions be moved into `cpp`?
</blockquote></details>

Not sure -- but if you don't see it in SMO then the function is probably inline. I think I'd call this "reset" rather than "remove".
___
*[`include/heap/seadHeapMgr.h` line 19 at r5](https://reviewable.io/reviews/open-ead/sead/105#-N8uJWvzE1kTZrZFXnZ6:-N8uJWw-4jmydWglDrbc:b-da5fgq) ([raw file](https://github.com/open-ead/sead/blob/7b2e3dafbbb7189fc4d1eac803b7c1c7c4bee527/include/heap/seadHeapMgr.h#L19)):*
> ```objc
> {
>     struct AllocFailedCallbackArg;
>     using IAllocFailedCallback = IDelegate1<const AllocFailedCallbackArg*>*;
> ```

This is actually not a pointer in Nintendo's code. We don't have to stick with their original choice (ofc) but considering we're using the original name, I think it'd be confusing for IAllocFailedCallback to be a pointer in our impl and not in the original.
___
*[`modules/src/heap/seadHeapMgr.cpp` line 233 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oT8rcEBnnrFLcbTBw:-N8uK_p08uQ2QXPM1vel:bk7uhw2) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L233)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Changed to auto*, where would you do what with braces?
</blockquote></details>

I'd remove the braces on the while loops, but that's a matter of personal preference I guess.
___
*[`modules/src/heap/seadHeapMgr.cpp` line 252 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oTEAH3m38MMkDgss9:-N8uKgKh33JMdRzIpbTP:b-1sfnrk) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L252)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

This does not work here for some reason:
```
auto lock = makeScopedLock(sHeapTreeLockCS);
```
=>
```
/home/monsterdruide1/OdysseyDecompSead/OdysseyDecomp/lib/sead/include/prim/seadScopedLock.h:21:12: error: call to deleted constructor of 'ScopedLock<sead::CriticalSection>'
    return ScopedLock<T>(&lock);
           ^~~~~~~~~~~~~~~~~~~~
/home/monsterdruide1/OdysseyDecompSead/OdysseyDecomp/lib/sead/modules/src/heap/seadHeapMgr.cpp:237:17: note: in instantiation of function template specialization 'sead::makeScopedLock<sead::CriticalSection>' requested here
    auto lock = makeScopedLock(sHeapTreeLockCS);
                ^
/home/monsterdruide1/OdysseyDecompSead/OdysseyDecomp/lib/sead/include/prim/seadScopedLock.h:10:5: note: 'ScopedLock' has been explicitly marked deleted here
    ScopedLock(const ScopedLock& other) = delete;
    ^
```
</blockquote></details>

Oof, looks like Clang 3.9 does not implement mandatory copy elision (a C++17 language change).

In C++17, compilers are required to omit the copy construction when doing `return ScopedLock<T>(...);`. Clang 3.9 doesn't have that core language feature implemented so it tries to invoke the copy constructor, which fails because ScopedLock is a non-copyable type. Let me fix ScopedLock for Clang 3.9...


<!-- Sent from Reviewable.io -->

2022-08-09 16:29 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/105)* status: all files reviewed, 7 unresolved discussions (waiting on @leoetlino and @MonsterDruide1)

___
*[`include/heap/seadHeapMgr.h` line 42 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oNjB5--Votxdt1zV7:-N92PdoAAgdgV3mxUyF1:b-qou4tp) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L42)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Grab a recent (but not too recent) APK of Super Mario Run and then extract libnn_piaPlugin.so from it. Then load the shared library into gdb (or another tool of your choice) to see the debug info.

With gdb the command you'll want to use to see debug info is `ptype`.

---

I see you have added the type alias, but don't forget to use it :)
</blockquote></details>

Okay, got it! What about the other `typedef`s?

```
378:    typedef pead::IDelegate1<pead::HeapMgr::AllocCallbackArg const*> pead::HeapMgr::IAllocCallback;
380:    typedef pead::IDelegate1<pead::HeapMgr::AllocFailedCallbackArg const*> pead::HeapMgr::IAllocFailedCallback;
384:    typedef pead::IDelegate1<pead::HeapMgr::CreateCallbackArg const*> pead::HeapMgr::ICreateCallback;
386:    typedef pead::IDelegate1<pead::HeapMgr::DestroyCallbackArg const*> pead::HeapMgr::IDestroyCallback;
382:    typedef pead::IDelegate1<pead::HeapMgr::FreeCallbackArg const*> pead::HeapMgr::IFreeCallback;
```
___
*[`include/heap/seadHeapMgr.h` line 43 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oNz1m3coNHniXg_X6:-N92PtSQ2kTWe1JH7ZCs:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L43)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

It's probably inline.
</blockquote></details>

Done.
___
*[`include/heap/seadHeapMgr.h` line 116 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oPNp13kkK73nxdDo9:-N92Q6Es-2IX4csggYhL:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L116)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Not sure -- but if you don't see it in SMO then the function is probably inline. I think I'd call this "reset" rather than "remove".
</blockquote></details>

Done.
___
*[`include/heap/seadHeapMgr.h` line 19 at r5](https://reviewable.io/reviews/open-ead/sead/105#-N8uJWvzE1kTZrZFXnZ6:-N92PPoK8yu7_NCEbSRd:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/7b2e3dafbbb7189fc4d1eac803b7c1c7c4bee527/include/heap/seadHeapMgr.h#L19)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This is actually not a pointer in Nintendo's code. We don't have to stick with their original choice (ofc) but considering we're using the original name, I think it'd be confusing for IAllocFailedCallback to be a pointer in our impl and not in the original.
</blockquote></details>

Done.
___
*[`modules/src/heap/seadHeapMgr.cpp` line 233 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oT8rcEBnnrFLcbTBw:-N92QoF502EYEbMdpUHw:bvto40g) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L233)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

I'd remove the braces on the while loops, but that's a matter of personal preference I guess.
</blockquote></details>

In my experience, removing braces from if is okay, but should be avoided on loops - but if you're okay with it, I'll happily remove those! Looks better for me as well.


<!-- Sent from Reviewable.io -->

2022-08-15 21:04 UTC, leoetlino requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/105)* status: all files reviewed, 3 unresolved discussions (waiting on @MonsterDruide1)

___
*[`include/heap/seadHeapMgr.h` line 42 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oNjB5--Votxdt1zV7:-N9YHMkY6xFI536VYW9X:b-iofs4d) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L42)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Okay, got it! What about the other `typedef`s?

```
378:    typedef pead::IDelegate1<pead::HeapMgr::AllocCallbackArg const*> pead::HeapMgr::IAllocCallback;
380:    typedef pead::IDelegate1<pead::HeapMgr::AllocFailedCallbackArg const*> pead::HeapMgr::IAllocFailedCallback;
384:    typedef pead::IDelegate1<pead::HeapMgr::CreateCallbackArg const*> pead::HeapMgr::ICreateCallback;
386:    typedef pead::IDelegate1<pead::HeapMgr::DestroyCallbackArg const*> pead::HeapMgr::IDestroyCallback;
382:    typedef pead::IDelegate1<pead::HeapMgr::FreeCallbackArg const*> pead::HeapMgr::IFreeCallback;
```
</blockquote></details>

Feel free to add and use them
___
*[`modules/src/heap/seadHeapMgr.cpp` line 94 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oRzBp1EReDXgfQ-NH:-N9YJCX20RKY-LMHGoTF:b-79gad) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L94)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

One of the first things I wanted to do in cleanup is the lock, but I can't figure out how that is handled. The method seems to be divided up into two parts, with the first one requiring the currentThread and the second one handling static variables `sRootHeaps` and `sIndependentHeaps`. However, I have no idea how the lock is carried between these two parts without unlocking and re-locking using a ScopedLock, so I'm lost on how to optimize this function - that's why I created the `decompme`, to allow you making quick suggestions on how to improve it.
</blockquote></details>

Unfortunately decomp.me is rather painful for large scratches (any BotW scratch basically). The function is also complex enough that you'd need to RE the original implementation of findContainHeap in IDA to even be able to figure out what's going on, let alone try to match it.
___
*[`modules/src/heap/seadHeapMgr.cpp` line 233 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oT8rcEBnnrFLcbTBw:-N9YIeaiAJ_CYPw__BzF:b-xqol2o) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L233)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

In my experience, removing braces from if is okay, but should be avoided on loops - but if you're okay with it, I'll happily remove those! Looks better for me as well.
</blockquote></details>

It doesn't really matter if it's an if or a loop. The relevant criteria is whether the if/loop body takes up more than one line.
___
*[`modules/src/heap/seadHeapMgr.cpp` line 252 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oTEAH3m38MMkDgss9:-N9YJ5J96mH9wudU4lk4:bbfjbfm) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L252)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Oof, looks like Clang 3.9 does not implement mandatory copy elision (a C++17 language change).

In C++17, compilers are required to omit the copy construction when doing `return ScopedLock<T>(...);`. Clang 3.9 doesn't have that core language feature implemented so it tries to invoke the copy constructor, which fails because ScopedLock is a non-copyable type. Let me fix ScopedLock for Clang 3.9...
</blockquote></details>

https://github.com/open-ead/sead/pull/106


<!-- Sent from Reviewable.io -->

2022-08-16 09:56 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/105)* status: all files reviewed, 3 unresolved discussions (waiting on @leoetlino)

___
*[`include/heap/seadHeapMgr.h` line 42 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oNjB5--Votxdt1zV7:-N9a3xep2NK8mM0cRMwL:bgc38sb) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/include/heap/seadHeapMgr.h#L42)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Feel free to add and use them
</blockquote></details>

Okay, added them, but there is no usage so far.
___
*[`modules/src/heap/seadHeapMgr.cpp` line 93 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oRgrs9rbxnL65d7PF:-N9a38Br71dwtyf3zs63:bhn2er7) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L93)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`current`
</blockquote></details>

(can be closed)
___
*[`modules/src/heap/seadHeapMgr.cpp` line 94 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oRzBp1EReDXgfQ-NH:-N9a2sM2-HEBDw6UOWmu:b3znndm) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L94)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Unfortunately decomp.me is rather painful for large scratches (any BotW scratch basically). The function is also complex enough that you'd need to RE the original implementation of findContainHeap in IDA to even be able to figure out what's going on, let alone try to match it.
</blockquote></details>

Okay, deleted it... :smiling_face_with_tear: 

Maybe we'll re-visit one day.
___
*[`modules/src/heap/seadHeapMgr.cpp` line 252 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oTEAH3m38MMkDgss9:-N9a45QU0bGiwryNaQ5y:b-aq8bd9) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L252)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

https://github.com/open-ead/sead/pull/106
</blockquote></details>

(still open, as newest suggestion does not compile)


<!-- Sent from Reviewable.io -->

2022-08-26 15:17 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/105)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @leoetlino)

___
*[`modules/src/heap/seadHeapMgr.cpp` line 252 at r2](https://reviewable.io/reviews/open-ead/sead/105#-N8oTEAH3m38MMkDgss9:-NAPidZX7nHUM9_PY110:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/583d6ea313f90ef4817bf61ca4d8718a5e68e8a8/modules/src/heap/seadHeapMgr.cpp#L252)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

(still open, as newest suggestion does not compile)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-27 23:17 UTC, leoetlino approved these changes
> Reviewed 4 of 4 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/105)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MonsterDruide1)



<!-- Sent from Reviewable.io -->

2022-08-27 23:17 UTC, merged