devenv: Add DebugFontMgr*Nvn
open-ead/sead pull request #122
Opened 2023-02-21 17:21 UTC by MonsterDruide1

Final changes from the `SuperMarioOdysseyOnline`-repo.

Missing functions marked in the `cpp`. Along with it, some functions weren't able to match completely:
- `ctor`+`createInstance` on both - Not only a difference in `C1`/`C2`, but also some instruction ordering.
- `begin` on both - Might have something to do with the `pfnc_nvn` reference, have these been tested before?

2023-02-21 21:59 UTC, ThePixelGamer commented
Don't use pfnc_, there's inline functions in one of the nvn headers that call the pointer (maybe this should be added to the guidelines) and I'll do a full review in a few hours

2023-02-22 01:13 UTC, ThePixelGamer commented on include/devenv/seadFontMgr.h
> +    float getHeight() const;
getHeight, getWidth, getCharWidth, getEncoding, getMaxDrawNum, begin, end, print are all virtual functions, I would implement these as abstract virtual functions in FontBase

2023-02-22 01:13 UTC, ThePixelGamer commented on include/gfx/seadDrawContext.h
>      u32 _8;
The only field here is nn::gfx::CommandBuffer, should be apparent in the DrawContext ctor

2023-02-22 01:13 UTC, ThePixelGamer commented on modules/src/devenv/seadFontMgr.cpp
> +    pfnc_nvnCommandBufferBindProgram(ctx->getNvnCommandBuffer(), &nvnProgram, 31);
Use the inline versions of these functions rather than the function pointers, causes different codegen

2023-02-22 01:13 UTC, ThePixelGamer commented on include/devenv/seadFontMgr.h
> +    NVNprogram nvnProgram;
NVNprogram should be sizeof(0xC0)?

2023-02-22 02:13 UTC, ThePixelGamer commented
Did some research into these 2 classes and came up with these 2 structs in ida, feel free to copy over whatever is needed
```cpp
struct sead::DebugFontMgrJis1Nvn
{
  void *__vftable;
  sead::IDisposer disposer;
  char _0[24];
  NVNprogram nvnProgram;
  NVNtexture nvnTexture;
  NVNtextureHandle nvnTextureHandle;
  NVNmemoryPool pool1;
  NVNmemoryPool pool2;
  NVNmemoryPool pool3;
  NVNbuffer buffer1;
  uint32_t bufferSize;
  void *fileData;
  NVNbuffer buffer2;
  void *buffer2Map;
  u32 _528;
  u32 _52c;
  uint8_t _530;
};

struct sead::DebugFontMgrNvn
{
  void *__vftable;
  sead::IDisposer disposer;
  char _0[24];
  NVNprogram nvnProgram;
  NVNtexture nvnTexture;
  NVNtextureHandle nvnTextureHandle;
  NVNmemoryPool pool1;
  NVNmemoryPool pool2;
  NVNmemoryPool pool3;
  NVNbuffer buffer1;
  u32 bufferSize;
  u32 _4e4;
  NVNbuffer buffer2;
  void *buffer2Map;
  u32 _520;
  u32 _524;
  uint8_t _528;
};
```

2023-02-22 09:49 UTC, MonsterDruide1 commented on include/devenv/seadFontMgr.h
> +    NVNprogram nvnProgram;
Yes, but the `SEAD_SINGLETON_DISPOSER` macro at the top also takes up some space, meaning that the element afterwards will start at `e8`.

2023-02-22 09:53 UTC, MonsterDruide1 commented
That fixed both `begin` functions! Any idea about the constructor, does something look off there? Especially the concept of `C1`/`C2`, that seems ... wrong.

For more context - it has the `C2` in game, but `C2` is empty in the decomp. Comparing against `C1` gives a different instruction order, but how can I force the `C2` to generate here?

2023-02-22 14:40 UTC, ThePixelGamer commented on modules/src/devenv/seadFontMgr.cpp
> +    nvnCommandBufferBindProgram(reinterpret_cast<NVNcommandBuffer*>(ctx->getCommandBuffer()->ToData()->pNvnCommandBuffer.ptr), &nvnProgram, 31);
This reinterpret cast isn't needed, drop it and the .ptr and it should compile correctly

2023-02-22 14:41 UTC, ThePixelGamer commented on include/devenv/seadFontMgr.h
> +    NVNprogram nvnProgram;
It takes up 32 bytes?

2023-02-22 14:43 UTC, ThePixelGamer commented
> That fixed both `begin` functions! Any idea about the constructor, does something look off there? Especially the concept of `C1`/`C2`, that seems ... wrong.
> 
> For more context - it has the `C2` in game, but `C2` is empty in the decomp. Comparing against `C1` gives a different instruction order, but how can I force the `C2` to generate here?

Unfortunately I'm not too sure, might have to ask Leo on discord

2023-02-22 15:52 UTC, MonsterDruide1 commented on include/devenv/seadFontMgr.h
> +    NVNprogram nvnProgram;
Well, it works and is correct like this, so I see this as a validation... I don't know the real size of the Disposer though.

2023-02-22 16:21 UTC, ThePixelGamer commented on include/devenv/seadFontMgr.h
> +    NVNprogram nvnProgram;
As long as the offset is correct then it's good for me

2023-02-22 16:32 UTC, ThePixelGamer commented
> For more context - it has the `C2` in game, but `C2` is empty in the decomp. Comparing against `C1` gives a different instruction order, but how can I force the `C2` to generate here?

while I'm not too sure how you can fix it I would start by fixing the member variables, some of the sets aren't being done (I've updated my research comment with the proper sets)

2023-02-22 16:53 UTC, ThePixelGamer requested changes

2023-02-22 16:53 UTC, ThePixelGamer commented on include/gfx/seadDrawContext.h
> +#include <nvn/nvn.h>
I don't think the nvn.h include is necessary here?

2023-02-22 16:53 UTC, ThePixelGamer commented on modules/src/devenv/seadFontMgr.cpp
> +    void* table_binary = reinterpret_cast<void*>(FileDeviceMgr::instance()->tryLoad(load_arg));
the casts from the returned u8* aren't necessary

2023-02-22 21:12 UTC, MonsterDruide1 commented
Adjusted the members according to your research, without a difference on codegen.

2023-02-23 07:16 UTC, ThePixelGamer approved these changes

2023-02-23 07:23 UTC, ThePixelGamer commented on modules/src/devenv/seadFontMgr.cpp
> +                                31);
NVN_SHADER_STAGE_ALL_GRAPHICS_BITS

2023-02-23 07:25 UTC, ThePixelGamer commented
I can't get it to match no matter what I do, I'll wait for leo's response in discord but after this last change is made it'll LGTM :shipit:

2023-02-24 09:42 UTC, MonsterDruide1 commented
Added a `UniformBlockBuffer` class as well, but I can't think of a good name or even the meaning of the variables in it.

2023-02-24 11:55 UTC, ThePixelGamer commented
> Added a `UniformBlockBuffer` class as well, but I can't think of a good name or even the meaning of the variables in it.

Remove the _8, if this class exists then it doesn't have it based on the other swap function

2023-02-24 13:27 UTC, MonsterDruide1 commented
Which other `swap` function? My first idea was something like that being a flag for whether something has actually been drawn in this buffer, so whether `begin` should map it in the first place... but something about that has a logical flaw, so I didn't label it like that, but I feel like it would really belong there.

Also, that `temp %=` was purposely avoided - as long as we don't know what each variable means, it doesn't really matter, but they probably have separate meanings and shouldn't be assigned to the same variable.

2023-02-25 00:47 UTC, ThePixelGamer commented
LGTM :shipit:

2023-02-25 00:47 UTC, merged