HeapMgr minor changes
open-ead/sead pull request #138
Opened 2024-06-02 12:51 UTC by Fuzzy2319

This PR adds needed changes for SMO HeapUtil functions.

https://github.com/Fuzzy2319/OdysseyDecomp/blob/HeapUtil/lib/al/src/Library/Memory/HeapUtil.cpp

2024-06-02 13:03 UTC, leoetlino commented
I think what you actually want is the scoped heap setter, but exposing setCurrentHeap sounds fine to me.

2024-06-02 13:04 UTC, MonsterDruide1 requested changes
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/138)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Fuzzy2319)

___
*[`include/heap/seadHeapMgr.h` line 28 at r1](https://reviewable.io/reviews/open-ead/sead/138#-NzO2Ahn-0TARdxgB_6w:-NzO2Ahn-0TARdxgB_6x:b1s9g5j) ([raw file](https://github.com/open-ead/sead/blob/63024e3fce9909d4db063026d5435a3bf28ef05e/include/heap/seadHeapMgr.h#L28)):*
> ```objc
> 
> public:
>     struct AllocFailedCallbackArg;
> ```

This is needed for `al::MemorySystem::allocFailedCallbackFunc(sead::HeapMgr::AllocFailedCallbackArg const*)`
___
*[`include/heap/seadHeapMgr.h` line 50 at r1](https://reviewable.io/reviews/open-ead/sead/138#-NzO1R3043iGlXMxaGwo:-NzO1R3043iGlXMxaGwp:b77sdqu) ([raw file](https://github.com/open-ead/sead/blob/63024e3fce9909d4db063026d5435a3bf28ef05e/include/heap/seadHeapMgr.h#L50)):*
> ```objc
>     static Heap* findHeapByName_(Heap*, const SafeString&, int* index);
>     Heap* getCurrentHeap() const;
>     Heap* setCurrentHeap(Heap* heap) { return setCurrentHeap_(heap); }
> ```

Might not be needed, if using `ScopedCurrentHeapSetter`.


<!-- Sent from Reviewable.io -->

2024-06-02 13:15 UTC, Fuzzy2319 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/138)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1)

___
*[`include/heap/seadHeapMgr.h` line 50 at r1](https://reviewable.io/reviews/open-ead/sead/138#-NzO1R3043iGlXMxaGwo:-NzO4rILEVaNhEeL78V5:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/63024e3fce9909d4db063026d5435a3bf28ef05e/include/heap/seadHeapMgr.h#L50)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Might not be needed, if using `ScopedCurrentHeapSetter`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-02 13:19 UTC, MonsterDruide1 approved these changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/138)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)



<!-- Sent from Reviewable.io -->

2024-06-06 21:33 UTC, leoetlino approved these changes

2024-06-06 21:33 UTC, merged