C++14 support (replacing C++17-only features)
open-ead/sead pull request #82
Opened 2021-07-15 22:23 UTC by MonsterDruide1

To support `clang-3.9.1` for building Super Mario Odyssey, `C++17` features have to be dropped. Here, this results in one major change:
As `string_view` gets unusable, the signatures of blocks in `modules/src/resource/seadSharcArchiveRes.cpp` can't be checked using that. Instead, `std::strncmp` is used then.

2021-07-15 22:35 UTC, leoetlino requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/82)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[modules/src/resource/seadSharcArchiveRes.cpp, line 229 at r1](https://reviewable.io/reviews/open-ead/sead/82#-MegHsE98JCIVZieK6BK:-MegHsE98JCIVZieK6BL:brkd72l) ([raw file](https://github.com/open-ead/sead/blob/7aac1f8ecdb7abf104ddbd6fc1976f87248fd2f7/modules/src/resource/seadSharcArchiveRes.cpp#L229)):*
> ```cpp
> 
>     mArchiveBlockHeader = reinterpret_cast<const ArchiveBlockHeader*>(archive_);
>     if(std::strncmp(mArchiveBlockHeader->signature, "SARC", 4) != 0)
> ```

formatting

Also, after checking on godbolt, please use std::memcmp rather than std::strncmp here -- memcmp gets lowered into a 32-bit load + comparison against 'SARC' (as a constant number) but strncmp requires a function call


<!-- Sent from Reviewable.io -->

2021-07-16 09:11 UTC, aboood40091 commented
Yeah, I noticed recently that this is a mistake on my part in the original sead because they used memcmp in sead.
The reason I made that mistake is due to confusion as I was also reverse-engineering nw::lyt at the time.
`nw::lyt::ArcExtractor::PrepareArchive()` is an exact match of `sead::SharcArchiveRes::prepareArchive_()` (Nintendo copying code between NintendoWare and sead again), except for a single difference which is that nw used strncmp, whereas sead used memcmp.

2021-07-16 10:40 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/82)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @leoetlino)

___
*[modules/src/resource/seadSharcArchiveRes.cpp, line 229 at r1](https://reviewable.io/reviews/open-ead/sead/82#-MegHsE98JCIVZieK6BK:-MeitmzUAcklkOe9vAQD:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/7aac1f8ecdb7abf104ddbd6fc1976f87248fd2f7/modules/src/resource/seadSharcArchiveRes.cpp#L229)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

formatting

Also, after checking on godbolt, please use std::memcpy rather than std::strncmp here -- memcpy gets lowered into a 32-bit load + comparison against 'SARC' (as a constant number) but strncmp requires a function call
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-16 11:55 UTC, leoetlino approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/82#-:-Mej9z2gDmwKhdBIO6FN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MonsterDruide1)



<!-- Sent from Reviewable.io -->

2021-07-16 11:56 UTC, merged