controller: Add `seadController`, `Base` and `Mgr`
open-ead/sead pull request #89
Opened 2021-12-09 22:26 UTC by MonsterDruide1

This PR adds some part of the input-related stuff into the decomp. These are the "frontend-classes", so the ones that games will most likely interact with. `SMO` uses another bunch of utility functions to read specific bits from the `seadControllerBase->mButtonTrigger`/... fields, so probably there is a similar system in place for other games too.

2021-12-09 23:49 UTC, leoetlino requested changes
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/89)* status: all files reviewed, 13 unresolved discussions (waiting on @MonsterDruide1)

___
*[include/controller/seadController.h, line 21 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqWZuQx-LXwv0TAAbq4:-MqWZuQx-LXwv0TAAbq5:bjbk57) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadController.h#L21)):*
> ```objc
> class Controller : public ControllerBase
> {
>     SEAD_RTTI_BASE(Controller)
> ```

Shouldn't this be OVERRIDE?
___
*[include/controller/seadController.h, line 27 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqW_3nv9HuwbPTbcvXI:-MqW_3nv9HuwbPTbcvXJ:b-cm0vul) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadController.h#L27)):*
> ```objc
>     virtual void calc();
>     virtual bool isConnected();
>     virtual void calcImpl_() = 0;
> ```

These 3 functions should probably be marked protected. (The _ suffix usually indicates protected/private members.)
___
*[include/controller/seadControllerBase.h, line 18 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqW_GYc92GK5UlQNP99:-MqW_GYc92GK5UlQNP9A:b-4dpy23) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerBase.h#L18)):*
> ```objc
>     void updateDerivativeParams_(u32, bool);
>     void setRightStickCrossThreshold(float, float);
>     void setPointerWithBound_(bool, bool, const sead::Vector2f&);
> ```

No need to qualify Vector2f — you're already in the sead namespace. Also you can give a name to the vector; it's obvious it should be called `bound`.
___
*[include/controller/seadControllerBase.h, line 24 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqWa8VbDDoZjG6BwcJ0:-MqWa8VbDDoZjG6BwcJ1:b1196ai) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerBase.h#L24)):*
> ```objc
>     void setIdleBase_();
>     bool isIdleBase_();
>     u32 getStickHold_(u32, const sead::Vector2f&, float, float, int); //unknown return type
> ```

This kind of comment should go above the line it is commenting because the line is already a bit long and clang-format tries to align trailing comments.
___
*[include/controller/seadControllerBase.h, line 33 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqW_W-u7PEqEeuFYZxK:-MqW_W-u7PEqEeuFYZxL:b2nhw2p) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerBase.h#L33)):*
> ```objc
>     unsigned int mButtonsRepeat;
>     unsigned int mFlags;
>     int field_18;
> ```

_18
___
*[include/controller/seadControllerBase.h, line 34 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqW_WgQATe0fp_e_b-q:-MqW_WgQATe0fp_e_b-r:bnx9fdr) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerBase.h#L34)):*
> ```objc
>     unsigned int mFlags;
>     int field_18;
>     int field_1C;
> ```

_1c (notice: lowercase c — this is important for consistency reasons and to avoid accidentally using reserved names)
___
*[include/controller/seadControllerBase.h, line 37 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqW_eLG346MI7TOnJog:-MqW_eLH68JO0dTgBBRC:b2nhx8o) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerBase.h#L37)):*
> ```objc
>     sead::BoundBox2<float> mPointerBound;
>     int mPadHoldCounts[32];
>     char field_B0[32];
> ```

_b0
___
*[include/controller/seadControllerBase.h, line 38 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqW_eti6Mzgy5z2xBo6:-MqW_eti6Mzgy5z2xBo7:bh075et) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerBase.h#L38)):*
> ```objc
>     int mPadHoldCounts[32];
>     char field_B0[32];
>     unsigned char field_D0[32];
> ```

_d0 (also just make this a char array if this is just padding/filler)
___
*[include/controller/seadControllerBase.h, line 43 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqW_rMx1wXJDaQGo-jh:-MqW_rMx1wXJDaQGo-ji:b-968p4u) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerBase.h#L43)):*
> ```objc
>     float mLeftStickThresholdY;
>     float mRightStickThresholdY;
>     int field_100;
> ```

_100 and so on below
___
*[include/controller/seadControllerBase.h, line 49 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqW_tXm7ErxIQRdnm3-:-MqW_tXm7ErxIQRdnm30:bd4by6w) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerBase.h#L49)):*
> ```objc
>     unsigned int mIdleCounter;
>     unsigned int mButtonsHold;
>     sead::Vector2<float> mTouchScreenPos;
> ```

no need to qualify
___
*[include/controller/seadControllerMgr.h, line 19 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqW_waS5qliBqLHBNyL:-MqW_waS5qliBqLHBNyM:bmxpxcd) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerMgr.h#L19)):*
> ```objc
>     SEAD_TASK_SINGLETON(ControllerMgr)
> public:
>     ControllerMgr(const TaskConstructArg&);
> ```

explicit. also please name the parameters wherever the name is obvious
___
*[include/controller/seadControllerMgr.h, line 27 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqWaL8M2eiUhg4kV4yj:-MqWaL8M2eiUhg4kV4yk:b-bcyptd) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerMgr.h#L27)):*
> ```objc
>     int findControllerPort(const Controller*);
>     NinJoyNpadDevice* getControlDevice(ControllerDefine::DeviceId);
>     void* getControllerAddon(int, ControllerDefine::AddonId);              // unknown return type
> ```

comment position
___
*[include/controller/seadControllerMgr.h, line 43 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqWaPEs9SZSCtgiaCYa:-MqWaPEs9SZSCtgiaCYb:bxi0qr0) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerMgr.h#L43)):*
> ```objc
> };
> 
> }  // namespace sead
> ```

This is missing a trailing newline.


<!-- Sent from Reviewable.io -->

2021-12-09 23:49 UTC, leoetlino commented
Also please (re?)run clang-format.

2021-12-10 08:22 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/89)* status: 1 of 4 files reviewed, 13 unresolved discussions (waiting on @leoetlino)

___
*[include/controller/seadController.h, line 21 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqWZuQx-LXwv0TAAbq4:-MqYPEPV9QTfBYrajEpp:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadController.h#L21)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Shouldn't this be OVERRIDE?
</blockquote></details>

Done.
___
*[include/controller/seadController.h, line 27 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqW_3nv9HuwbPTbcvXI:-MqYPQXc9ucHZ8xpk8vw:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadController.h#L27)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

These 3 functions should probably be marked protected. (The _ suffix usually indicates protected/private members.)
</blockquote></details>

Done.
___
*[include/controller/seadControllerBase.h, line 18 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqW_GYc92GK5UlQNP99:-MqYQ9fS6VxTq2EgpQ_c:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerBase.h#L18)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

No need to qualify Vector2f — you're already in the sead namespace. Also you can give a name to the vector; it's obvious it should be called `bound`.
</blockquote></details>

Done.
___
*[include/controller/seadControllerBase.h, line 24 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqWa8VbDDoZjG6BwcJ0:-MqYQASF6L1yXaErpvr-:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerBase.h#L24)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This kind of comment should go above the line it is commenting because the line is already a bit long and clang-format tries to align trailing comments.
</blockquote></details>

Done.
___
*[include/controller/seadControllerBase.h, line 33 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqW_W-u7PEqEeuFYZxK:-MqYQLBI258l_uA3GJ3g:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerBase.h#L33)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

_18
</blockquote></details>

Done.
___
*[include/controller/seadControllerBase.h, line 34 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqW_WgQATe0fp_e_b-q:-MqYQLQLCCx1Y_20Ybi0:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerBase.h#L34)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

_1c (notice: lowercase c — this is important for consistency reasons and to avoid accidentally using reserved names)
</blockquote></details>

Done.
___
*[include/controller/seadControllerBase.h, line 37 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqW_eLG346MI7TOnJog:-MqYQM9zCETT5Rr5IaHK:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerBase.h#L37)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

_b0
</blockquote></details>

Done.
___
*[include/controller/seadControllerBase.h, line 38 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqW_eti6Mzgy5z2xBo6:-MqYQNgq96DFDXiii7h2:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerBase.h#L38)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

_d0 (also just make this a char array if this is just padding/filler)
</blockquote></details>

Done.
___
*[include/controller/seadControllerBase.h, line 43 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqW_rMx1wXJDaQGo-jh:-MqYQOuU5YLu-udSh5OC:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerBase.h#L43)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

_100 and so on below
</blockquote></details>

Done.
___
*[include/controller/seadControllerBase.h, line 49 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqW_tXm7ErxIQRdnm3-:-MqYQPRx8NWEhv7W51SR:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerBase.h#L49)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

no need to qualify
</blockquote></details>

Done.
___
*[include/controller/seadControllerMgr.h, line 19 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqW_waS5qliBqLHBNyL:-MqYQafW9ga5dR1PV37Y:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerMgr.h#L19)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

explicit. also please name the parameters wherever the name is obvious
</blockquote></details>

Done.
___
*[include/controller/seadControllerMgr.h, line 27 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqWaL8M2eiUhg4kV4yj:-MqYPj64CpzmrVM2t077:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerMgr.h#L27)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

comment position
</blockquote></details>

Done.
___
*[include/controller/seadControllerMgr.h, line 43 at r2](https://reviewable.io/reviews/open-ead/sead/89#-MqWaPEs9SZSCtgiaCYa:-MqYPikbDJmsg9nR1llQ:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04507206cef26021ddb87af90643337ba2a78925/include/controller/seadControllerMgr.h#L43)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This is missing a trailing newline.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-10 11:56 UTC, leoetlino requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/89)* status: all files reviewed, 12 unresolved discussions (waiting on @MonsterDruide1)

___
*[include/controller/seadControllerBase.h, line 17 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZB-xA9EXl-V1hEzMo:-MqZB-xA9EXl-V1hEzMp:biif4w5) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerBase.h#L17)):*
> ```objc
> 
>     void setRightStickCrossThreshold(float, float);
>     void setPointerBound(const BoundBox2<float>&);
> ```

`BoundBox2f` (also this is still missing the parameter name)
___
*[include/controller/seadControllerBase.h, line 21 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBcYpA7KzJOl7gcs5:-MqZBcYpA7KzJOl7gcs6:b574r5a) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerBase.h#L21)):*
> ```objc
>     void setLeftStickCrossThreshold(float, float);
>     // unknown return type
>     u32 getPadHoldCount(int);
> ```

should be const
___
*[include/controller/seadControllerBase.h, line 23 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBdOkCVKSpWSjNmyI:-MqZBdOkCVKSpWSjNmyJ:b3uxeb8) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerBase.h#L23)):*
> ```objc
>     u32 getPadHoldCount(int);
> 
>     int getButtonsTrigger() { return mButtonsTrigger; }
> ```

const (ditto below)
___
*[include/controller/seadControllerBase.h, line 27 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZB6-l30b3WW0rQR46:-MqZB6-l30b3WW0rQR47:b-toyhql) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerBase.h#L27)):*
> ```objc
>     int getButtonsRepeat() { return mButtonsRepeat; }
>     int getButtonsHold() { return mButtonsHold; }
>     Vector2<float>* getTouchScreenPos() { return &mTouchScreenPos; }
> ```

`Vector2f` -- also I'd expect this to return a const-ref and be const-qualified. Same remarks below.
___
*[include/controller/seadControllerBase.h, line 48 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBhsrCW232D5l3fZj:-MqZBhsrCW232D5l3fZk:b-cgxcoq) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerBase.h#L48)):*
> ```objc
>     int _18;
>     int _1c;
>     BoundBox2<float> mPointerBound;
> ```

BoundBox2f
___
*[include/controller/seadControllerBase.h, line 62 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBijG4R91BcQ2szLt:-MqZBijG4R91BcQ2szLu:b-2nff1g) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerBase.h#L62)):*
> ```objc
>     unsigned int mIdleCounter;
>     unsigned int mButtonsHold;
>     Vector2<float> mTouchScreenPos;
> ```

Vector2f
___
*[include/controller/seadControllerMgr.h, line 26 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBlnk17EBJMok7Thg:-MqZBlnk17EBJMok7Thh:b-e39fwh) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerMgr.h#L26)):*
> ```objc
>     void finalizeDefault();
>     int findControllerPort(const Controller* controller);
>     NinJoyNpadDevice* getControlDevice(ControllerDefine::DeviceId deviceId);
> ```

device_id
___
*[include/controller/seadControllerMgr.h, line 28 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBl3p49Zai9y0NE0d:-MqZBl3qCWnfCyHUitNd:bfzuy67) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerMgr.h#L28)):*
> ```objc
>     NinJoyNpadDevice* getControlDevice(ControllerDefine::DeviceId deviceId);
>     // unknown return type
>     void* getControllerAddon(int, ControllerDefine::AddonId addonId);
> ```

addon_id
___
*[include/controller/seadControllerMgr.h, line 30 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBn0d1Zk7Ue5JR-Od:-MqZBn0d1Zk7Ue5JR-Oe:bfzuy67) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerMgr.h#L30)):*
> ```objc
>     void* getControllerAddon(int, ControllerDefine::AddonId addonId);
>     // unknown return type
>     void* getControllerAddonByOrder(int, ControllerDefine::AddonId addonId, int);
> ```

addon_id
___
*[include/controller/seadControllerMgr.h, line 31 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBnk_DwNCrjre1vay:-MqZBnk_DwNCrjre1vaz:b-1ts5l3) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerMgr.h#L31)):*
> ```objc
>     // unknown return type
>     void* getControllerAddonByOrder(int, ControllerDefine::AddonId addonId, int);
>     Controller* getControllerByOrder(ControllerDefine::ControllerId controllerId, int);
> ```

controller_id
___
*[include/controller/seadControllerMgr.h, line 34 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBwt_02edDuSQ12t0:-MqZBwt_02edDuSQ12t1:b-u77xtw) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerMgr.h#L34)):*
> ```objc
>     // unknown return type, probably inherited from TaskBase
>     void* getFramework();
>     void initialize(int, Heap*);
> ```

parameter name for heap
___
*[include/controller/seadControllerMgr.h, line 35 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBy8L1_YvIeaLXba0:-MqZBy8L1_YvIeaLXba1:b-u77xtw) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerMgr.h#L35)):*
> ```objc
>     void* getFramework();
>     void initialize(int, Heap*);
>     void initializeDefault(Heap*);
> ```

parameter name for heap


<!-- Sent from Reviewable.io -->

2021-12-10 12:03 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/89)* status: all files reviewed, 12 unresolved discussions (waiting on @leoetlino)

___
*[include/controller/seadControllerBase.h, line 17 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZB-xA9EXl-V1hEzMo:-MqZCr7bAFzGf7Pk-erZ:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerBase.h#L17)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`BoundBox2f` (also this is still missing the parameter name)
</blockquote></details>

Done.
___
*[include/controller/seadControllerBase.h, line 21 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBcYpA7KzJOl7gcs5:-MqZCrMc8Ko1mP0UZoO-:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerBase.h#L21)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

should be const
</blockquote></details>

Done.
___
*[include/controller/seadControllerBase.h, line 23 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBdOkCVKSpWSjNmyI:-MqZCrgI86MbGlRym9zw:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerBase.h#L23)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

const (ditto below)
</blockquote></details>

Done.
___
*[include/controller/seadControllerBase.h, line 27 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZB6-l30b3WW0rQR46:-MqZCvPG87fBLdsqk3ZG:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerBase.h#L27)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`Vector2f` -- also I'd expect this to return a const-ref and be const-qualified. Same remarks below.
</blockquote></details>

Done.
___
*[include/controller/seadControllerBase.h, line 48 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBhsrCW232D5l3fZj:-MqZDFUVE6ZokyjffU_n:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerBase.h#L48)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

BoundBox2f
</blockquote></details>

Done.
___
*[include/controller/seadControllerBase.h, line 62 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBijG4R91BcQ2szLt:-MqZDGDp9Srhx7mpOGmD:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerBase.h#L62)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Vector2f
</blockquote></details>

Done.
___
*[include/controller/seadControllerMgr.h, line 26 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBlnk17EBJMok7Thg:-MqZDNZW7r2bfD8HsPZf:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerMgr.h#L26)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

device_id
</blockquote></details>

Done.
___
*[include/controller/seadControllerMgr.h, line 28 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBl3p49Zai9y0NE0d:-MqZDNFU516r5XFHPp1V:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerMgr.h#L28)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

addon_id
</blockquote></details>

Done.
___
*[include/controller/seadControllerMgr.h, line 30 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBn0d1Zk7Ue5JR-Od:-MqZDN4A8SjLfcMDy-xt:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerMgr.h#L30)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

addon_id
</blockquote></details>

Done.
___
*[include/controller/seadControllerMgr.h, line 31 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBnk_DwNCrjre1vay:-MqZDMw84YbSS7FwIo3y:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerMgr.h#L31)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

controller_id
</blockquote></details>

Done.
___
*[include/controller/seadControllerMgr.h, line 34 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBwt_02edDuSQ12t0:-MqZDOel9MRWtNaybqIX:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerMgr.h#L34)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

parameter name for heap
</blockquote></details>

Done.
___
*[include/controller/seadControllerMgr.h, line 35 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZBy8L1_YvIeaLXba0:-MqZDOXaEmeAs66GLDm6:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerMgr.h#L35)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

parameter name for heap
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-10 12:05 UTC, leoetlino requested changes
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/89)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @leoetlino and @MonsterDruide1)

___
*[include/controller/seadControllerBase.h, line 27 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZB6-l30b3WW0rQR46:-MqZDmf-88V51UP0CJdJ:butyiis) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerBase.h#L27)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why does this return a pointer instead of a reference?


<!-- Sent from Reviewable.io -->

2021-12-10 12:05 UTC, leoetlino commented
#54, #55, #56

2021-12-10 12:08 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/89)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @leoetlino)

___
*[include/controller/seadControllerBase.h, line 27 at r3](https://reviewable.io/reviews/open-ead/sead/89#-MqZB6-l30b3WW0rQR46:-MqZEanL7g8cFME42goQ:b-apm5qv) ([raw file](https://github.com/open-ead/sead/blob/1ac124d282ea584b3e79ad529cd20682c6170057/include/controller/seadControllerBase.h#L27)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Why does this return a pointer instead of a reference?
</blockquote></details>

Good question... fixed, changed to a reference.


<!-- Sent from Reviewable.io -->

2021-12-10 12:10 UTC, leoetlino approved these changes
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/89)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MonsterDruide1)



<!-- Sent from Reviewable.io -->

2021-12-10 12:12 UTC, merged