Change button bit flag type to BitFlag32 and add setCursorFromTopLeft to TextWriter
open-ead/sead pull request #94
Opened 2022-01-27 07:12 UTC by iTNTPiston

2022-01-27 09:52 UTC, leoetlino requested changes

2022-01-27 09:52 UTC, leoetlino commented on include/controller/seadControllerBase.h
> +    const sead::BitFlag32 getButtonsTrigger() const { return mButtonsTrigger; }
Const-qualifying the return type is not useful here because the value is returned by copy anyway.
```suggestion
    BitFlag32 getButtonsTrigger() const { return mButtonsTrigger; }
```
Also just BitFlag32 is enough since you're in sead.

2022-02-03 11:21 UTC, iTNTPiston reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/94)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @leoetlino)

___
*[include/controller/seadControllerBase.h, line 23 at r1](https://reviewable.io/reviews/open-ead/sead/94#-MuPNBM2x-jE4DfEjlWE-r1-23:-MuzJKzb3TXDaY98GeZP:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/a4d9e965ea6151c1d59bb4bf10c9724f900ce3c4/include/controller/seadControllerBase.h#L23)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Const-qualifying the return type is not useful here because the value is returned by copy anyway.
```suggestion
    BitFlag32 getButtonsTrigger() const { return mButtonsTrigger; }
```
Also just BitFlag32 is enough since you're in sead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-03 11:22 UTC, leoetlino approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/94)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iTNTPiston)



<!-- Sent from Reviewable.io -->

2022-02-03 11:23 UTC, merged